load('//:subdir_glob.bzl', 'subdir_glob')

cxx_library(
  name = 'mathutils',
  header_namespace = 'mathutils',
  exported_headers = subdir_glob([
    ('include', '**/*.hpp'),
  ]),
  srcs = glob([
    'src/**/*.cpp',
  ]),
  visibility = [
    '//...',
  ],
)
